- README.md
- adala/agents/base.py
- adala/environments/base.py
- adala/memories/__init__.py
- adala/memories/base.py
- adala/memories/file_memory.py
- adala/runtimes/base.py
- adala/skills/base.py
- adala/skills/skillset.py
- adala/utils/internal_data.py
- adala/utils/matching.py
- docs/src/index.md
- examples/classification_skill.ipynb
- examples/classification_skill_with_CoT.ipynb
- examples/linear_skill_program.ipynb
- examples/question_answering_skill.ipynb
- examples/quickstart.ipynb
- examples/summarization_skill.ipynb
- examples/text_generation_skill.ipynb
- examples/translation_skill.ipynb
- tests/test_agent_basics.py
- tests/test_classification.py
- tests/test_environments.py
- tests/test_llm_skillset.py
- tests/utils.py
The idea of this PR is to specify the linear skill set and to make it trainable on the basic ground truth environment, for example:
```
from adala.agents import Agent
from adala.skills import LinearSkillSet
agent = Agent(
skills=LinearSkillSet(skills=[
'Identify keywords that best describe the meaning of the text',
'Generate new text based on the keywords'
])
)
agent.environment = BasicEnvironment(ground_truth_dataset=Dataset(df=df))
agent.learn()
```
> Adding the ability to learn multiple skills simultaneously

- adala/runtimes/_openai.py
Bugfix - `/submit` requests to the server were failing with the following stack trace:
```
app-1   | ERROR:  Exception in ASGI application
app-1   | Traceback (most recent call last):
app-1   |  File "/usr/src/app/.venv/lib/python3.11/site-packages/anyio/streams/memory.py", line 98, in receive
app-1   |   return self.receive_nowait()
app-1   |       ^^^^^^^^^^^^^^^^^^^^^
app-1   |  File "/usr/src/app/.venv/lib/python3.11/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
app-1   |   raise WouldBlock
app-1   | anyio.WouldBlock
app-1   | 
app-1   | During handling of the above exception, another exception occurred:
app-1   | 
app-1   | Traceback (most recent call last):
app-1   |  File "/usr/src/app/.venv/lib/python3.11/site-packages/starlette/middleware/base.py", line 78, …
```
> Fix unpickleable fields due to openai client

- Dockerfile.app
- adala/environments/kafka.py
- docker-compose.yml
- poetry.lock
- pyproject.toml
- server/app.py
- server/handlers/result_handlers.py
- server/tasks/process_file.py
- server/utils.py
- add Label Studio SDK as a dependency (should be an optional dependency for the server only, but there's no clean way to do this in poetry)
- switch ResultHandlers from an enum whitelist of functions to a registry of Pydantic models, same implementation as Environment/Skill/Runtime
- add LSEHandler that pushes predictions to an LS project using an LS SDK Client
- change celery worker functions to use pickle serialization, removing manual step of de/serializing objects on each worker call from an API endpoint
- change utils and handlers import paths to be usable from both main app and celery workers
- make AsyncKafkaEnvironment instantiable as prep for post-streaming refactoring
> feat: DIA-953: Stream results from adala inference server into LSE

- Dockerfile.app
- adala/runtimes/_openai.py
> fix dockerfile not building due to PEP517 error

- adala/agents/base.py
Otherwise this code requires us to create an dummy async environment which is not used in the code and not even possible with the current code base.
> Running agent.arun(input=df) with environment=None is totally valid.

- server/app.py
- server/tasks/process_file.py
- server/utils.py
We observed an issue where the list of kafka topics was growing on develop Adala instance, even though we implemented logic to delete them after completing a job. However, we did not handle the case of a job failing, or being canceled. I have added a handler to be run when the parent_streaming_task fails, so that we clean up topics, and also cleaning up topics when we cancel a job.
Also added logic to attempt to stop input/output jobs when the parent task fails.
> fix: DIA-1168: Delete kafka topics on job failure / cancel

- server/tasks/process_file.py
- server/utils.py
Add server-side timeout to all Celery tasks. We already have an LSE timeout of 30 minutes, but this will catch individual Celery tasks that are orphaned (don't have a parent task available to cancel them) due to <3 workers being available when the job is started. 
Since the timeout applies to in progress jobs (that are waiting on sending/receiving kafka messages), setting a very loose default timeout of 24 hours.
> Add server-side timeout

- server/utils.py
consumer timeouts - reduce time to first record w/ tradeoff of increased change that a long-running record is dropped
(longest running record -> exponential retry backoff w/ max of 1sec)
task timeout - reduce potential number of zombie jobs w/ tradeoff of increased chance of canceling a long-running job
(longest projected job -> 10k records has worst case 10 mins from load test, so 100k records would be <2hrs)
> change consumer timeouts to 1.5sec and task timeout to 6hrs

- adala/skills/__init__.py
- server/app.py
- server/handlers/result_handlers.py
- tests/test_server.py
- Parameterized tests for `/submit-streaming`
- Breaking change: Changed output LSE payload behavior to ensure we can process structured outputs of arbitrary number of fields and field names
- Added request error handler in server
> feat: DIA-1323: Pass NER tasks from Adala server to Adala's Entity Extraction during Inference Run

- adala/runtimes/_litellm.py
- adala/utils/exceptions.py
1. Specifying to instructor/tenacity to not retry on pydantic ValidationError 
2. When this case is hit, raising a custom exception to return to LSE - ContrainedGenerationError
> fix: DIA-1334: Catch and report pydantic ValidationError

- adala/runtimes/_litellm.py
Currently when we are printing the traceback for exceptions caught we were using `traceback.format_exc` which uses `*sys.exc_info()` instead of accepting an exception object itself. For some reason in this flow, this was returning None. Now using `traceback.format_exception()` which DOES take an exception object argument, and will return the traceback as a list of strings. Current just printing it (like `traceback.print_exception()` but might be useful to send back to LSE in the future
> fix: DIA-1441: RecursionError better traceback logging

- adala/runtimes/_litellm.py
- adala/skills/_base.py
- adala/skills/collection/rag.py
- adala/utils/parse.py
- tests/cassettes/test_llm/test_llm_sync.yaml
- tests/test_llm.py
use partial_str_format util to exclude extra {} from string formatting
This commonly happens in autorefined prompts which include instructions about the JSON response format.
> fix: DIA-1534: prompts containing {} throw an error

- adala/agents/base.py
- adala/skills/_base.py
- adala/skills/collection/prompt_improvement.py
- server/app.py
- tests/test_refine_skill.py
fix /improve-prompt request to not require a jobid, as a job has not yet been created
> feat: DIA-1511: Support data batch context for autorefinement

- adala/environments/kafka.py
- server/app.py
- server/tasks/stream_inference.py
- tests/test_stream_inference.py
acks='all' ensures that all replicas have written the message that is produced 
group_id for consumers is to allow multiple consumers to consume from the same topic. In this case we have a 1-to-1 relationship and each group_id should be unique in order to properly track the offset for each topic
manual offset committing in the consumer seems to have solved the issue. 4 in a row runs with 10k/10k outputs. 
We still need the `time.sleep(0.1)` in the submit_batch endpoint, without it we still hit the same offset issue on the consumer side... unclear why exactly.
> fix: DIA-1556: Not getting predictions for all tasks

- adala/skills/collection/prompt_improvement.py
fall back to a default label config
> fix: DIA-1489: backwards compatible autorefinement with non-multiskill

- server/app.py
- server/tasks/stream_inference.py
- server/utils.py
- tests/test_stream_inference.py
set https://docs.celeryq.dev/en/v5.4.0/userguide/workers.html#max-memory-per-child-setting so that when a child process hits 1GB, which is about 60% of the total memory limit for the whole worker, it is gracefully restarted after the current task finishes. Plus some cleanup and logging.
> fix: DIA-1619: logging and graceful handling for memory leaks

- adala/runtimes/_litellm.py
Instructor upstream error handling has changed
- ValidationErrors don't contain the string we were checking with multiskill
- instructor bug leads to them sometimes being reported as AttributeError
> fix: DIA-1660: Adala errors are not reported as ConstrainedGenerationError when they should be

- adala/runtimes/__init__.py
- adala/runtimes/_litellm.py
- adala/runtimes/_openai.py
- adala/skills/collection/label_studio.py
- tests/cassettes/test_label_studio_skill/test_label_studio_skill_image_input.yaml
- tests/cassettes/test_llm/test_vision_runtime.yaml
- tests/test_label_studio_skill.py
- tests/test_llm.py
[x] parse input variables to split message based on media type
[x] plumb up vision runtime
[x] generalize error handling
[x] let LabelStudioSkill set input variable types
[x] add tests
> feat: DIA-1450: Image Classification support in adala

- adala/skills/collection/label_studio.py
- server/app.py
- tests/test_serialization.py
- tests/test_stream_inference.py
We are filtering in LabelStudioSkill.validate_response_model based on `allowed_control_tags` and `allowed_object_tags` but not overwriting `self.label_config` based on this - only `self.field_schema` 
Now checking to make sure any `Labels` tag points to a compatible object tag
> fix: DIA-1637: Check object tag compatibility for NER tags

- server/utils.py
Increase input topic timeout to allow time for generating presigned urls.
Opting to increase this rather than decrease the batch size more, as a temporary solution.
> fix: DIA-1739: increase kafka input topic timeout

- adala/skills/collection/label_studio.py
- server/utils.py
- tests/cassettes/test_label_studio_skill/test_label_studio_skill_image_input.yaml
- tests/test_label_studio_skill.py
We were not flagging inputs as image URLs correctly when the tag name and variable name differed, leading to the text of the image URL being fed to the prompt. Fixed this while avoiding changing the LSE<->adala API; will refactor later when we've settled on a better idea of what we need for image inputs to avoid code duplication. Ideally we wouldn't need to know so much about the LSE data model here.
> fix: DIA-1738: Aws_access_key_id is displayed in Evaluation results

- adala/runtimes/_litellm.py
o3-mini does not support `max_tokens` or `temperature` so making those params optional
> feat: DIA-1886: Add o3-mini OpenAI model

- adala/environments/kafka.py
- docker-compose.native.yml
- tests/cassettes/test_stream_inference/test_run_streaming.yaml
- tests/test_stream_inference.py
Even with increased max message size compared to default, it is possible to hit MessageTooSizeLarge errors. Now depending on the size of the message we will split it into as many chunks as we need and send them one by one 
Removing redis from native docker compose as we have it in LSE and don't need another one here.
> fix: DIA-1911: Gracefully handle large Kafka messages

- adala/skills/collection/entity_extraction.py
- adala/utils/parse.py
- tests/test_parse.py
Added new simpler string formatter with state. Should resolve errors in cost estimation, inference, refinement caused by weird prompt/tasks. See updated tests for new behavior.
>  fix: DIA-1885: edge cases in string parsing

- adala/utils/parse.py
This keeps from failing to determine text input types on multimodal projects
> fix: DIA-2021: use defaultdict for input_field_types instead of dict

- poetry.lock
- pyproject.toml
Fixed bug in litellm here: https://github.com/HumanSignal/litellm/commit/dc819af506e7e02e94488b3021e5aab09c4bb889
Updating version to include this fix.
> fix: DIA-2029: Cost calculation bug

- server/handlers/result_handlers.py
Added num_failed_predictions to batch-failed-predictions post request, to be able to capture in metabase
> feat: DIA-2131: Capture num failed predictions sent to LSE

- poetry.lock
- pyproject.toml
- server/utils.py
Don't want to support 2 different libraries' formats for SSL, so to simplify implementation, use `aiokafka` for everything
> feat: DIA-1996: remove sync kafka library

- server/utils.py
Previously, due to using subsettings, environment variables without the appropriate prefix would shadow ones with the prefix. For example, if `REDIS_URL` is not set, `URL -> REDIS_URL`.
This change prevents picking up unintended env vars.
> fix: DIA-1996: make settings variables less permissive

- server/app.py
- tests/cassettes/test_server/test_chat_completion_endpoint_api_client.yaml
- tests/cassettes/test_server/test_chat_completion_endpoint_error_handling.yaml
- tests/cassettes/test_server/test_chat_completion_endpoint_openai_client.yaml
- tests/cassettes/test_server/test_custom_provider_with_anthropic_endpoint.yaml
- tests/conftest.py
- tests/test_server.py
**Before:**
Only a single `api_key` string can be passed in `/chat/completions` endpoint via headers or JSON body
**After:**
- Complex JSON payloads (e.g., where more than one credential string is required, like with VertexAI connections) are supported.
- The JSON body parameter has been removed to tighten security controls.
> feat: BROS-357: User can select provider/model for <Chat>
